trigger:
- main

pool:
  name: 'poolp'

steps:

- checkout: self

- script: mvn clean package
  displayName: 'Build Maven Project'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    testResultsFormat: 'JUnit'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target'
    ArtifactName: 'drop'
    publishLocation: 'Container'